In [1]:
import torch 
import torch.nn as nn

class Linear_Regression(nn.Module):
    def __init__(self, input_size, output_size):
        super(Linear_Regression, self).__init__()
        
        self.linear = nn.Linear(input_size, output_size)
        
        
    def forward(self,x):
        y_hat = self.linear(x)
        return y_hat
    
    

In [2]:
model = Linear_Regression(1,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.3311]], requires_grad=True), Parameter containing:
tensor([-0.1890], requires_grad=True)]


In [3]:
x = torch.tensor([3.0], requires_grad = True)
y_hat = model(x)
y_hat

tensor([0.8043], grad_fn=<AddBackward0>)

In [5]:
model = Linear_Regression(3, 1)    # three input features vector with one output vetor

x = torch.randn(3,3)
y_hat = model(x)
y_hat

tensor([[-0.1821],
        [ 0.3788],
        [ 0.1434]], grad_fn=<AddmmBackward0>)

In [6]:
model.state_dict()

OrderedDict([('linear.weight', tensor([[-0.5658, -0.3468, -0.2041]])),
             ('linear.bias', tensor([0.5385]))])

# Training in PyTorch