# Tensor, size, dtype, ndim

In [1]:
import torch 

a = torch.tensor([0,1,2,3,4,5])
a 

tensor([0, 1, 2, 3, 4, 5])

In [2]:
# Data attribute
a.dtype 

torch.int64

In [3]:
# Method type
a.type()

'torch.LongTensor'

In [4]:
a.size()

torch.Size([6])

In [5]:
a.ndim 

1

In [6]:
a.ndimension()

1

In [7]:
b = torch.tensor([0,1,2,3,4,5], dtype = torch.float16)
b 

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float16)

In [8]:
b.dtype

torch.float16

In [9]:
b.type()

'torch.HalfTensor'

In [10]:
b.size()

torch.Size([6])

In [11]:
b.ndim

1

In [12]:
# reshaping the tensor 
b_col = b.view(6,1) 
b_col 

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.]], dtype=torch.float16)

In [13]:
b_col.size()

torch.Size([6, 1])

In [14]:
b_col.ndim

2

In [15]:
# reshaping another way
a_col = a.view(-1,1)
a_col.ndim 

2

In [16]:
a_col.size()

torch.Size([6, 1])

In [17]:
# Numpy to tensor and vice-versa

import numpy as np 


numpy_array = np.array([0,1,2,3,4,5])
numpy_array

array([0, 1, 2, 3, 4, 5])

In [18]:
torch_array = torch.from_numpy(numpy_array)
torch_array

tensor([0, 1, 2, 3, 4, 5], dtype=torch.int32)

In [19]:
# Back to numpy
numpy_array = torch_array.numpy()
numpy_array

array([0, 1, 2, 3, 4, 5])

In [20]:
# Similarly pandas series can be changed into tensor

import pandas as pd 

pandas_series = pd.Series([0.1,2,0.3,10])
pandas_series


0     0.1
1     2.0
2     0.3
3    10.0
dtype: float64

In [21]:
pandas_to_tensor = torch.from_numpy(pandas_series.values)
pandas_to_tensor

tensor([ 0.1000,  2.0000,  0.3000, 10.0000], dtype=torch.float64)

# Slicing and Indexing

In [22]:
b[0:]

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float16)

In [23]:
b[-1]

tensor(5., dtype=torch.float16)

In [24]:
b[0:4]

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [25]:
b[0] = 23
b 

tensor([23.,  1.,  2.,  3.,  4.,  5.], dtype=torch.float16)

# 2D - Tensor

In [26]:
array = torch.tensor([[1,2,3], [4,5,6]])
array

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
array.ndim

2

In [28]:
array.size()

torch.Size([2, 3])

In [29]:
array[0]  ## first row

tensor([1, 2, 3])

In [30]:
array[:,0] ## first column

tensor([1, 4])

In [31]:
flatt = array.flatten()  #flatten
flatt 

tensor([1, 2, 3, 4, 5, 6])

In [32]:
reshaped_array = torch.reshape(flatt, (2,3))   # reshape
reshaped_array

tensor([[1, 2, 3],
        [4, 5, 6]])

In [33]:
random_matrix = np.random.rand(3,3)    # random matrix
random_matrix = torch.from_numpy(random_matrix)
random_matrix

tensor([[0.8267, 0.7941, 0.9822],
        [0.7396, 0.4081, 0.0278],
        [0.5800, 0.7801, 0.9452]], dtype=torch.float64)

In [34]:
random_matrix = np.random.randint(1,100, size = (3,3))    # random integer matrix
random_matrix = torch.from_numpy(random_matrix)
random_matrix

tensor([[30, 79, 52],
        [62, 76, 71],
        [46, 40, 79]], dtype=torch.int32)

# Derivatives in pytorch

In [35]:
# consider quadratic function f(x) = x^2, the derivatic of the function is f'(x) = 2*x

x = torch.tensor(2.0, requires_grad = True)  # define the value of x first
y = x**2
y.backward()    # y' = 2*x 
x.grad          # y' = 2*2 = 4 

tensor(4.)

In [36]:
x = torch.tensor(3.0, requires_grad = True)
z = x**2 + 2*x + 1
z.backward()        # z' = 2*z + 2
x.grad              # z' = 2*3 + 2 = 8

tensor(8.)

# Partial derivatives 

In [37]:
# f(u, v) = uv + u**2

# f(u, v) w.r.t u = v + 2*u
# f(u, v) w.r.t v = u 



u = torch.tensor(1.0 , requires_grad = True)
v = torch.tensor(2.0,  requires_grad = True)

f = u*v + u**2   # define the function
f.backward()     # f' =  v + 2*u, f' = v
print(u.grad)
print(v.grad)

tensor(4.)
tensor(1.)


# Dataset in PyTorch

In [38]:
import torch 
import torchvision.datasets as dataset 
from torchvision.transforms import ToTensor

train_data = dataset.MNIST(root = './data', train = True, download = True, transform = ToTensor())
